import { HttpClient, HttpParams } from '@angular/common/http';
import { Injectable, inject, signal } from '@angular/core';
import { Observable, of } from 'rxjs';
import { environment } from '../../../environments/environment';
import { AuthService } from './auth.service';
import { AssignedStudent, AssignedTeacher, Course, CoursePayload, Department, Enrollment, PageResponse, ProfileAssignment } from '../models/api.models';

const departments: Department[] = [
  {id:'d1',code:'CSE',name:'Computer Science and Engineering',description:'Computing, software, and intelligent systems.',studentCount:206,teacherCount:22,courseCount:19,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},
  {id:'d2',code:'ECE',name:'Electronic Engineering',description:'Electronics and embedded systems.',studentCount:184,teacherCount:18,courseCount:15,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},
];
const courses: Course[] = [
  {id:'c1',code:'CSE-2103',name:'Programming Fundamentals',semester:'FIRST',academicYear:'2026-2027',departmentId:'d1',departmentCode:'CSE',departmentName:'Computer Science and Engineering',teacherId:'t1',teacherUserId:'u2',teacherName:'John Smith',enrollmentCount:52,createdAt:'',updatedAt:''},
];

@Injectable({providedIn:'root'})
export class AcademicService {
  private http=inject(HttpClient); private auth=inject(AuthService);
  private previewDepartments=signal(departments); private previewCourses=signal(courses); private previewEnrollments=signal<Enrollment[]>([]);private previewAssignedTeachers=signal<AssignedTeacher[]>([]);private previewAssignedStudents=signal<AssignedStudent[]>([]);
  departments(query='',page=0,size=20):Observable<PageResponse<Department>>{if(this.auth.isPreview())return of(this.page(this.previewDepartments().filter(x=>`${x.code} ${x.name}`.toLowerCase().includes(query.toLowerCase())),page,size));return this.http.get<PageResponse<Department>>(`${environment.apiUrl}/departments`,{params:{query,page,size}})}
  getDepartment(id:string):Observable<Department>{if(this.auth.isPreview())return of(this.previewDepartments().find(x=>x.id===id)!);return this.http.get<Department>(`${environment.apiUrl}/departments/${id}`)}
  createDepartment(body:Pick<Department,'code'|'name'|'description'>):Observable<Department>{if(this.auth.isPreview()){const x={...body,id:crypto.randomUUID(),studentCount:0,teacherCount:0,courseCount:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};this.previewDepartments.update(v=>[x,...v]);return of(x)}return this.http.post<Department>(`${environment.apiUrl}/departments`,body)}
  updateDepartment(id:string,body:Pick<Department,'code'|'name'|'description'>):Observable<Department>{if(this.auth.isPreview()){const old=this.previewDepartments().find(x=>x.id===id)!;const x={...old,...body};this.previewDepartments.update(v=>v.map(y=>y.id===id?x:y));return of(x)}return this.http.put<Department>(`${environment.apiUrl}/departments/${id}`,body)}
  deleteDepartment(id:string):Observable<void>{if(this.auth.isPreview()){this.previewDepartments.update(v=>v.filter(x=>x.id!==id));return of(undefined)}return this.http.delete<void>(`${environment.apiUrl}/departments/${id}`)}
  departmentTeachers(departmentId:string,query='',page=0,size=20):Observable<PageResponse<AssignedTeacher>>{if(this.auth.isPreview())return of(this.page(this.previewAssignedTeachers().filter(x=>x.departmentId===departmentId&&this.matchesMember(x,query)),page,size));return this.http.get<PageResponse<AssignedTeacher>>(`${environment.apiUrl}/departments/${departmentId}/teachers`,{params:{query,page,size}})}
  departmentStudents(departmentId:string,query='',page=0,size=20):Observable<PageResponse<AssignedStudent>>{if(this.auth.isPreview())return of(this.page(this.previewAssignedStudents().filter(x=>x.departmentId===departmentId&&this.matchesMember(x,query)),page,size));return this.http.get<PageResponse<AssignedStudent>>(`${environment.apiUrl}/departments/${departmentId}/students`,{params:{query,page,size}})}
  courses(query='',page=0,size=20,filters:Partial<Pick<Course,'departmentId'|'teacherId'|'semester'|'academicYear'>>={}):Observable<PageResponse<Course>>{if(this.auth.isPreview())return of(this.page(this.previewCourses().filter(x=>`${x.code} ${x.name}`.toLowerCase().includes(query.toLowerCase())),page,size));let params=new HttpParams().set('query',query).set('page',page).set('size',size);Object.entries(filters).forEach(([key,value])=>{if(value)params=params.set(key,value)});return this.http.get<PageResponse<Course>>(`${environment.apiUrl}/courses`,{params})}
  getCourse(id:string):Observable<Course>{if(this.auth.isPreview())return of(this.previewCourses().find(x=>x.id===id)!);return this.http.get<Course>(`${environment.apiUrl}/courses/${id}`)}
  createCourse(body:CoursePayload):Observable<Course>{if(this.auth.isPreview()){const d=this.previewDepartments().find(x=>x.id===body.departmentId)!;const x:Course={...body,id:crypto.randomUUID(),departmentCode:d?.code||'',departmentName:d?.name||'',teacherUserId:'',teacherName:'Selected teacher',enrollmentCount:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};this.previewCourses.update(v=>[x,...v]);return of(x)}return this.http.post<Course>(`${environment.apiUrl}/courses`,body)}
  updateCourse(id:string,body:CoursePayload):Observable<Course>{if(this.auth.isPreview()){const old=this.previewCourses().find(x=>x.id===id)!;const d=this.previewDepartments().find(x=>x.id===body.departmentId)!;const x={...old,...body,departmentCode:d?.code||'',departmentName:d?.name||''};this.previewCourses.update(v=>v.map(y=>y.id===id?x:y));return of(x)}return this.http.put<Course>(`${environment.apiUrl}/courses/${id}`,body)}
  deleteCourse(id:string):Observable<void>{if(this.auth.isPreview()){this.previewCourses.update(v=>v.filter(x=>x.id!==id));return of(undefined)}return this.http.delete<void>(`${environment.apiUrl}/courses/${id}`)}
  enrollments(courseId:string,page=0,size=100):Observable<PageResponse<Enrollment>>{if(this.auth.isPreview())return of(this.page(this.previewEnrollments().filter(x=>x.courseId===courseId),page,size));return this.http.get<PageResponse<Enrollment>>(`${environment.apiUrl}/courses/${courseId}/enrollments`,{params:{page,size}})}
  enroll(courseId:string,studentId:string):Observable<Enrollment>{if(this.auth.isPreview()){const x:Enrollment={id:crypto.randomUUID(),courseId,courseCode:'',courseName:'',studentId,studentUserId:'',studentNumber:'Preview',studentName:'Preview Student',enrolledAt:new Date().toISOString()};this.previewEnrollments.update(v=>[x,...v]);return of(x)}return this.http.post<Enrollment>(`${environment.apiUrl}/courses/${courseId}/enrollments`,{studentId})}
  unenroll(courseId:string,studentId:string):Observable<void>{if(this.auth.isPreview()){this.previewEnrollments.update(v=>v.filter(x=>!(x.courseId===courseId&&x.studentId===studentId)));return of(undefined)}return this.http.delete<void>(`${environment.apiUrl}/courses/${courseId}/enrollments/${studentId}`)}
  assignDepartment(kind:'students'|'teachers',departmentId:string,profileId:string):Observable<ProfileAssignment>{if(this.auth.isPreview()){const result=this.previewAssignment(kind,departmentId,profileId);const d=this.previewDepartments().find(x=>x.id===departmentId)!;if(kind==='teachers')this.previewAssignedTeachers.update(all=>all.some(x=>x.teacherId===profileId)?all:[...all,{teacherId:profileId,userId:result.userId,employeeNumber:result.referenceNumber,email:'teacher@sam.edu',firstName:'Preview',lastName:'Teacher',fullName:result.fullName,departmentId,departmentCode:d?.code||'',departmentName:d?.name||''}]);else this.previewAssignedStudents.update(all=>all.some(x=>x.studentId===profileId)?all:[...all,{studentId:profileId,userId:result.userId,studentNumber:result.referenceNumber,email:'student@sam.edu',firstName:'Preview',lastName:'Student',fullName:result.fullName,departmentId,departmentCode:d?.code||'',departmentName:d?.name||''}]);return of(result)}return this.http.put<ProfileAssignment>(`${environment.apiUrl}/departments/${departmentId}/${kind}/${profileId}`,{})}
  unassignDepartment(kind:'students'|'teachers',departmentId:string,profileId:string):Observable<ProfileAssignment>{if(this.auth.isPreview()){if(kind==='teachers')this.previewAssignedTeachers.update(all=>all.filter(x=>x.teacherId!==profileId));else this.previewAssignedStudents.update(all=>all.filter(x=>x.studentId!==profileId));return of({...this.previewAssignment(kind,departmentId,profileId),departmentId:null,departmentName:null})}return this.http.delete<ProfileAssignment>(`${environment.apiUrl}/departments/${departmentId}/${kind}/${profileId}`)}
  private previewAssignment(kind:'students'|'teachers',departmentId:string,profileId:string):ProfileAssignment{const d=this.previewDepartments().find(x=>x.id===departmentId);return{profileId,userId:'preview-user',fullName:kind==='teachers'?'Preview Teacher':'Preview Student',referenceNumber:kind==='teachers'?'TCH-001':'STU-001',departmentId,departmentName:d?.name||'Preview Department'}}
  private matchesMember(member:{employeeNumber?:string;studentNumber?:string;email:string;firstName:string;lastName:string},query:string){const haystack=`${member.employeeNumber||member.studentNumber||''} ${member.email} ${member.firstName} ${member.lastName}`.toLowerCase();return haystack.includes(query.trim().toLowerCase())}
  private page<T>(all:T[],page:number,size:number):PageResponse<T>{return{content:all.slice(page*size,page*size+size),page,size,totalElements:all.length,totalPages:Math.ceil(all.length/size),first:page===0,last:(page+1)*size>=all.length}}
}
