import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Injectable, inject, signal } from '@angular/core';
import { Observable, of } from 'rxjs';
import { environment } from '../../../environments/environment';
import { AttendancePercentagePeriod, AttendanceRecord, AttendanceReport, AttendanceSession, PageResponse, SessionPayload, StudentAttendancePercentageReport } from '../models/api.models';
import { AuthService } from './auth.service';
import { PREVIEW_SESSIONS } from './attendance.service';

export interface AttendanceFilters { courseId?:string; teacherId?:string; studentId?:string; sessionId?:string; departmentId?:string; date?:string; status?:string; month?:string; from?:string; to?:string; page?:number; size?:number; }
export interface StudentPercentageFilters { period:AttendancePercentagePeriod; date:string; courseId?:string; query?:string; page?:number; size?:number; }
@Injectable({providedIn:'root'})
export class AttendanceAdminService{
  private http=inject(HttpClient);private auth=inject(AuthService);private previewSessions=signal([...PREVIEW_SESSIONS]);
  sessions(filters:AttendanceFilters={}):Observable<PageResponse<AttendanceSession>>{if(this.auth.isPreview())return of(this.page(this.previewSessions(),filters.page||0,filters.size||100));return this.http.get<PageResponse<AttendanceSession>>(`${environment.apiUrl}/attendance-sessions`,{params:this.params(filters)})}
  createSession(body:SessionPayload):Observable<AttendanceSession>{if(this.auth.isPreview()){const x:AttendanceSession={id:crypto.randomUUID(),...body,courseCode:'PREVIEW',courseName:'Preview Course',teacherId:'',teacherUserId:'',teacherName:'Preview Teacher',status:'SCHEDULED',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};this.previewSessions.update(v=>[x,...v]);return of(x)}return this.http.post<AttendanceSession>(`${environment.apiUrl}/attendance-sessions`,body)}
  updateSession(id:string,body:SessionPayload):Observable<AttendanceSession>{if(this.auth.isPreview()){const old=this.previewSessions().find(x=>x.id===id)!;const x={...old,...body};this.previewSessions.update(v=>v.map(y=>y.id===id?x:y));return of(x)}return this.http.put<AttendanceSession>(`${environment.apiUrl}/attendance-sessions/${id}`,body)}
  action(id:string,action:'start'|'close'|'cancel'):Observable<AttendanceSession>{if(this.auth.isPreview()){const status=action==='start'?'ACTIVE':action==='close'?'CLOSED':'CANCELLED';const old=this.previewSessions().find(x=>x.id===id)!;const x={...old,status} as AttendanceSession;this.previewSessions.update(v=>v.map(y=>y.id===id?x:y));return of(x)}return this.http.post<AttendanceSession>(`${environment.apiUrl}/attendance-sessions/${id}/${action}`,{})}
  deleteSession(id:string):Observable<void>{if(this.auth.isPreview()){this.previewSessions.update(v=>v.filter(x=>x.id!==id));return of(undefined)}return this.http.delete<void>(`${environment.apiUrl}/attendance-sessions/${id}`)}
  records(filters:AttendanceFilters={}):Observable<PageResponse<AttendanceRecord>>{if(this.auth.isPreview())return of(this.page([],filters.page||0,filters.size||100));return this.http.get<PageResponse<AttendanceRecord>>(`${environment.apiUrl}/attendance`,{params:this.params(filters)})}
  record(id:string):Observable<AttendanceRecord>{return this.http.get<AttendanceRecord>(`${environment.apiUrl}/attendance/${id}`)}
  report(filters:AttendanceFilters={}):Observable<AttendanceReport>{if(this.auth.isPreview()){const records=this.page<AttendanceRecord>([],0,50);return of({totalRecords:47,expectedAttendance:50,attendanceRate:94,generatedAt:new Date().toISOString(),records})}return this.http.get<AttendanceReport>(`${environment.apiUrl}/reports/attendance`,{params:this.params(filters)})}
  export(format:'pdf'|'excel',filters:AttendanceFilters):Observable<HttpResponse<Blob>>{return this.http.get(`${environment.apiUrl}/reports/attendance/export/${format}`,{params:this.params(filters),observe:'response',responseType:'blob'})}
  studentPercentages(filters:StudentPercentageFilters):Observable<StudentAttendancePercentageReport>{if(this.auth.isPreview()){const rows=[{studentId:'preview-student',studentUserId:'preview-user',studentNumber:'STU-001',studentName:'Mia Anderson',courseId:'c1',courseCode:'CSE-2103',courseName:'Programming Fundamentals',totalSessions:12,presentSessions:11,absentSessions:1,attendancePercentage:91.67}];return of({period:filters.period,referenceDate:filters.date,from:filters.date,to:filters.date,generatedAt:new Date().toISOString(),students:this.page(rows,filters.page||0,filters.size||20)})}return this.http.get<StudentAttendancePercentageReport>(`${environment.apiUrl}/reports/attendance/students`,{params:this.percentageParams(filters,true)})}
  exportStudentPercentages(format:'pdf'|'excel',filters:StudentPercentageFilters):Observable<HttpResponse<Blob>>{const accept=format==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';return this.http.get(`${environment.apiUrl}/reports/attendance/students/export/${format}`,{params:this.percentageParams(filters,false),headers:{Accept:accept},observe:'response',responseType:'blob'})}
  private params(filters:AttendanceFilters):HttpParams{let p=new HttpParams();Object.entries(filters).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')p=p.set(k,String(v))});if(!p.has('page'))p=p.set('page','0');if(!p.has('size'))p=p.set('size','100');return p}
  private percentageParams(filters:StudentPercentageFilters,paged:boolean):HttpParams{let p=new HttpParams().set('period',filters.period).set('date',filters.date);if(filters.courseId)p=p.set('courseId',filters.courseId);if(filters.query)p=p.set('query',filters.query);if(paged)p=p.set('page',String(filters.page||0)).set('size',String(filters.size||20));return p}
  private page<T>(all:T[],page:number,size:number):PageResponse<T>{return{content:all.slice(page*size,page*size+size),page,size,totalElements:all.length,totalPages:Math.ceil(all.length/size),first:page===0,last:(page+1)*size>=all.length}}
}
